import traceback
import sys
import pandas as pd
# try:
#     1/0
# except Exception:
#     traceback.print_exc()
    
# print("aqui")

# df_kb_c = pd.read_csv(sys.path[0] + "/output/" + "kb_characteristics.csv", sep=",")

# df_kb_c.at[0, 'dataset'] = 'x.dat'

# print(df_kb_c)
